// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Event struct {
	EventID          int32     `json:"event_id"`
	OrganizerID      int32     `json:"organizer_id"`
	EventName        string    `json:"event_name"`
	EventDescription string    `json:"event_description"`
	Duration         int32     `json:"duration"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type TimeSlotsEvent struct {
	ID        int32     `json:"id"`
	EventID   int32     `json:"event_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

type TimeSlotsUser struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

type User struct {
	UserID    int32     `json:"user_id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}
