// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateTimeSlotEvent(ctx context.Context, arg CreateTimeSlotEventParams) (TimeSlotsEvent, error)
	CreateTimeSlotUser(ctx context.Context, arg CreateTimeSlotUserParams) (TimeSlotsUser, error)
	CreateUser(ctx context.Context, name string) (User, error)
	DeleteEvent(ctx context.Context, eventID int32) error
	DeleteTimeSlotEvent(ctx context.Context, arg DeleteTimeSlotEventParams) error
	DeleteTimeSlotUser(ctx context.Context, arg DeleteTimeSlotUserParams) error
	GetEventByID(ctx context.Context, eventID int32) (Event, error)
	GetTimeSlotsByEvent(ctx context.Context, eventID int32) ([]TimeSlotsEvent, error)
	GetTimeSlotsByUser(ctx context.Context, userID int32) ([]TimeSlotsUser, error)
	GetTimeSlotsForAllUsers(ctx context.Context) ([]GetTimeSlotsForAllUsersRow, error)
	GetUserByID(ctx context.Context, userID int32) (User, error)
	ListEvents(ctx context.Context) ([]Event, error)
	ListEventsByOrganizer(ctx context.Context, organizerID int32) ([]Event, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) error
	UpdateTimeSlotEvent(ctx context.Context, arg UpdateTimeSlotEventParams) error
	UpdateTimeSlotUser(ctx context.Context, arg UpdateTimeSlotUserParams) error
}

var _ Querier = (*Queries)(nil)
