// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateTimeSlotEvent(ctx context.Context, arg CreateTimeSlotEventParams) (TimeSlotsEvent, error)
	CreateTimeSlotUser(ctx context.Context, arg CreateTimeSlotUserParams) (TimeSlotsUser, error)
	CreateUser(ctx context.Context, name string) (User, error)
	DeleteEvent(ctx context.Context, eventID int32) error
	DeleteTimePreferenceEvent(ctx context.Context, arg DeleteTimePreferenceEventParams) error
	DeleteTimePreferenceUser(ctx context.Context, arg DeleteTimePreferenceUserParams) error
	GetEventByID(ctx context.Context, eventID int32) (Event, error)
	GetTimePreferencesByEvent(ctx context.Context, eventID int32) ([]TimeSlotsEvent, error)
	GetTimePreferencesByUser(ctx context.Context, userID int32) ([]TimeSlotsUser, error)
	GetTimePreferencesForAllUsers(ctx context.Context) ([]GetTimePreferencesForAllUsersRow, error)
	GetUserByID(ctx context.Context, userID int32) (User, error)
	ListEvents(ctx context.Context) ([]Event, error)
	ListEventsByOrganizer(ctx context.Context, organizerID int32) ([]Event, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) error
	UpdateTimePreferenceEvent(ctx context.Context, arg UpdateTimePreferenceEventParams) error
	UpdateTimePreferenceUser(ctx context.Context, arg UpdateTimePreferenceUserParams) error
}

var _ Querier = (*Queries)(nil)
