// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	AddEventParticipant(ctx context.Context, arg AddEventParticipantParams) error
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateTimePreference(ctx context.Context, arg CreateTimePreferenceParams) (TimePreference, error)
	CreateUser(ctx context.Context, name string) (User, error)
	DeleteEvent(ctx context.Context, eventID int32) error
	DeleteTimePreferenceByID(ctx context.Context, id int32) error
	DeleteTimePreferenceByUnique(ctx context.Context, arg DeleteTimePreferenceByUniqueParams) error
	DeleteUser(ctx context.Context, userID int32) error
	GetEventByID(ctx context.Context, eventID int32) (Event, error)
	GetEventParticipants(ctx context.Context, eventID int32) ([]EventParticipant, error)
	GetParticipantStatus(ctx context.Context, arg GetParticipantStatusParams) (EventParticipant, error)
	GetTimePreferenceByID(ctx context.Context, id int32) (TimePreference, error)
	GetTimePreferencesByOwner(ctx context.Context, arg GetTimePreferencesByOwnerParams) ([]TimePreference, error)
	GetUserByID(ctx context.Context, userID int32) (User, error)
	ListEvents(ctx context.Context) ([]Event, error)
	ListEventsByOrganizer(ctx context.Context, organizerID int32) ([]Event, error)
	ListUserEvents(ctx context.Context, userID int32) ([]EventParticipant, error)
	ListUsers(ctx context.Context) ([]User, error)
	RemoveEventParticipant(ctx context.Context, arg RemoveEventParticipantParams) error
	UpdateAttendanceStatus(ctx context.Context, arg UpdateAttendanceStatusParams) error
	UpdateEventDescription(ctx context.Context, arg UpdateEventDescriptionParams) error
	UpdateTimePreference(ctx context.Context, arg UpdateTimePreferenceParams) error
	UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error
}

var _ Querier = (*Queries)(nil)
