// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: time_slots_event.sql

package db

import (
	"context"
	"time"
)

const createTimeSlotEvent = `-- name: CreateTimeSlotEvent :one
INSERT INTO time_slots_event (event_id, start_time, end_time)
VALUES ($1, $2, $3)
RETURNING id, event_id, start_time, end_time
`

type CreateTimeSlotEventParams struct {
	EventID   int32     `json:"event_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) CreateTimeSlotEvent(ctx context.Context, arg CreateTimeSlotEventParams) (TimeSlotsEvent, error) {
	row := q.db.QueryRowContext(ctx, createTimeSlotEvent, arg.EventID, arg.StartTime, arg.EndTime)
	var i TimeSlotsEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteTimePreferenceEvent = `-- name: DeleteTimePreferenceEvent :exec
DELETE FROM time_slots_event
WHERE id = $1 AND event_id = $2
`

type DeleteTimePreferenceEventParams struct {
	ID      int32 `json:"id"`
	EventID int32 `json:"event_id"`
}

func (q *Queries) DeleteTimePreferenceEvent(ctx context.Context, arg DeleteTimePreferenceEventParams) error {
	_, err := q.db.ExecContext(ctx, deleteTimePreferenceEvent, arg.ID, arg.EventID)
	return err
}

const getTimePreferencesByEvent = `-- name: GetTimePreferencesByEvent :many
SELECT id, event_id, start_time, end_time
FROM time_slots_event
WHERE event_id = $1
ORDER BY start_time
`

func (q *Queries) GetTimePreferencesByEvent(ctx context.Context, eventID int32) ([]TimeSlotsEvent, error) {
	rows, err := q.db.QueryContext(ctx, getTimePreferencesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TimeSlotsEvent{}
	for rows.Next() {
		var i TimeSlotsEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimePreferenceEvent = `-- name: UpdateTimePreferenceEvent :exec
UPDATE time_slots_event
SET start_time = $3, end_time = $4
WHERE id = $1 AND event_id = $2
`

type UpdateTimePreferenceEventParams struct {
	ID        int32     `json:"id"`
	EventID   int32     `json:"event_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) UpdateTimePreferenceEvent(ctx context.Context, arg UpdateTimePreferenceEventParams) error {
	_, err := q.db.ExecContext(ctx, updateTimePreferenceEvent,
		arg.ID,
		arg.EventID,
		arg.StartTime,
		arg.EndTime,
	)
	return err
}
